services:
  - type: web
    name: sports-event-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: SPORTS_API_KEY
        sync: false
      - key: FOOTBALL_API_KEY
        sync: false
      - key: CRICKET_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: API_PROVIDER
        value: balldontlie 